import Babel from "@babel/standalone";
import type { EvidenceEnvelope, ExecutionMetadata, RuntimeFamilyDescriptor } from "./contracts";
import { REACT_RUNTIME_PROTOCOL_VERSION, RUNTIME_LIMITS, encodedBytes, isProtocolMessage, type RuntimeResultMessage } from "./react-sandbox/protocol";
export interface ReactRunRequest { source: string; revision?: number; runId?: string; props?: Record<string, unknown>; timeoutMs?: number; }
export interface ReactRunResult { execution: ExecutionMetadata; root: null; dom: string; runtimeError: string | null; console: readonly string[]; renderCount: number; networkAttempts: readonly string[]; parentAccess: readonly string[]; evidence: EvidenceEnvelope; }
export const REACT_COMPONENT_BROWSER_DESCRIPTOR: RuntimeFamilyDescriptor = { family: "component-browser", version: 1, security: "browser-sandbox", capabilities: [{ name: "execute.react", version: 1 }, { name: "render.dom", version: 1 }, { name: "inspect.dom", version: 1 }, { name: "inspect.console", version: 1 }, { name: "interact.allowlisted", version: 1 }, { name: "reset.run", version: 1 }] };
export { REACT_RUNTIME_PROTOCOL_VERSION, RUNTIME_LIMITS };
let revision = 0;
export function resetReactRevision() { revision += 1; return revision; }
export function isCurrentReactRun(runRevision: number) { return runRevision === revision; }
function boundedProps(value: Record<string, unknown>) { if (encodedBytes(value) > RUNTIME_LIMITS.propsBytes) return null; try { const serialized = JSON.stringify(value); return serialized ? JSON.parse(serialized) as Record<string, unknown> : null; } catch { return null; } }
function makeEvidence(result: ReactRunResult): EvidenceEnvelope { return { schemaVersion: 1, runId: result.execution.runId, revision: result.execution.revision, family: "component-browser", phase: "observe", timestamp: Date.now(), status: result.runtimeError ? "partial" : "complete", source: { host: "isolated-iframe", artifactIds: [] }, items: [{ kind: "dom-snapshot", html: result.dom }, { kind: "console", level: "log", message: result.console.join("\n") }, { kind: "js-value", expression: "renderCount", value: result.renderCount }, { kind: "js-value", expression: "networkAttempts", value: [...result.networkAttempts] }, ...(result.runtimeError ? [{ kind: "runtime-error" as const, message: result.runtimeError }] : [])] }; }
function runtimeUrl(nonce: string, runId: string, runRevision: number) { return `/react-runtime.html?${new URLSearchParams({ nonce, runId, revision: String(runRevision) })}`; }
export function runReactComponent(request: ReactRunRequest): Promise<ReactRunResult | null> { const runRevision = request.revision ?? resetReactRevision(); if (!isCurrentReactRun(runRevision) || encodedBytes(request.source) > RUNTIME_LIMITS.sourceBytes) return Promise.resolve(null); const runId = request.runId ?? `react-${runRevision}`, nonce = crypto.randomUUID(), requestId = crypto.randomUUID(), props = boundedProps(request.props ?? {}); if (!props) return Promise.resolve(null); let transformed = ""; try { transformed = Babel.transform(request.source, { presets: [["react", { runtime: "classic" }], "typescript"], filename: "lesson.tsx" }).code ?? ""; } catch { return Promise.resolve(null); } return new Promise((resolve) => { const startedAt = Date.now(), iframe = document.createElement("iframe"); iframe.setAttribute("sandbox", "allow-scripts"); iframe.title = "Isolated React lesson runtime"; iframe.src = runtimeUrl(nonce, runId, runRevision); let settled = false, ready = false; const finish = (response: RuntimeResultMessage | null, status: "succeeded" | "failed" | "timeout") => { if (settled) return; settled = true; window.clearTimeout(timeoutId); iframe.contentWindow?.postMessage({ type: "runtime:dispose", protocolVersion: REACT_RUNTIME_PROTOCOL_VERSION, runId, revision: runRevision, nonce }, "*"); window.removeEventListener("message", onMessage); iframe.remove(); const runtimeError = response?.runtimeError ?? (status === "timeout" ? "React execution timed out." : null); const result = { execution: { schemaVersion: 1, runId, revision: runRevision, family: "component-browser" as const, phase: "run" as const, status, startedAt, completedAt: Date.now(), artifacts: [], ...(runtimeError ? { error: runtimeError } : {}) }, root: null, dom: response?.dom ?? "", runtimeError, console: response?.console ?? [], renderCount: response?.renderCount ?? 0, networkAttempts: response?.networkAttempts ?? [], parentAccess: response?.parentAccess ?? [], evidence: {} as EvidenceEnvelope }; result.evidence = makeEvidence(result); resolve(result); }; const onMessage = (event: MessageEvent) => { const message = event.data; if (!isProtocolMessage(message) || event.source !== iframe.contentWindow || message.runId !== runId || message.revision !== runRevision || message.nonce !== nonce) return; if (message.type === "runtime:ready") { ready = true; iframe.contentWindow?.postMessage({ type: "runtime:execute", protocolVersion: REACT_RUNTIME_PROTOCOL_VERSION, runId, revision: runRevision, nonce, requestId, source: transformed, props }, "*"); } else if (message.type === "runtime:result" && ready && message.requestId === requestId) finish(message, message.runtimeError ? "failed" : "succeeded"); }; window.addEventListener("message", onMessage); document.body.appendChild(iframe); const timeoutId = window.setTimeout(() => finish(null, "timeout"), Math.min(Math.max(request.timeoutMs ?? RUNTIME_LIMITS.timeoutMs, 1), RUNTIME_LIMITS.timeoutMs)); }); }
