/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as QuizzesRouteImport } from './routes/quizzes'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as MentorRouteImport } from './routes/mentor'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as InterviewRouteImport } from './routes/interview'
import { Route as FlashcardsRouteImport } from './routes/flashcards'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DebugLabRouteImport } from './routes/debug-lab'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizzesQuizIdRouteImport } from './routes/quizzes.$quizId'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as LessonLessonIdRouteImport } from './routes/lesson.$lessonId'
import { Route as LearnTopicsRouteImport } from './routes/learn.topics'
import { Route as LearnModulesRouteImport } from './routes/learn.modules'
import { Route as LearnLessonsRouteImport } from './routes/learn.lessons'
import { Route as InterviewSessionRouteImport } from './routes/interview.session'
import { Route as DebugLabBugIdRouteImport } from './routes/debug-lab.$bugId'

const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesRoute = QuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorRoute = MentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRoute = InterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsRoute = FlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugLabRoute = DebugLabRouteImport.update({
  id: '/debug-lab',
  path: '/debug-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesQuizIdRoute = QuizzesQuizIdRouteImport.update({
  id: '/$quizId',
  path: '/$quizId',
  getParentRoute: () => QuizzesRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const LessonLessonIdRoute = LessonLessonIdRouteImport.update({
  id: '/lesson/$lessonId',
  path: '/lesson/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnTopicsRoute = LearnTopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => LearnRoute,
} as any)
const LearnModulesRoute = LearnModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => LearnRoute,
} as any)
const LearnLessonsRoute = LearnLessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => LearnRoute,
} as any)
const InterviewSessionRoute = InterviewSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => InterviewRoute,
} as any)
const DebugLabBugIdRoute = DebugLabBugIdRouteImport.update({
  id: '/$bugId',
  path: '/$bugId',
  getParentRoute: () => DebugLabRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/bookmarks': typeof BookmarksRoute
  '/challenges': typeof ChallengesRoute
  '/debug-lab': typeof DebugLabRouteWithChildren
  '/docs': typeof DocsRoute
  '/flashcards': typeof FlashcardsRoute
  '/interview': typeof InterviewRouteWithChildren
  '/learn': typeof LearnRouteWithChildren
  '/mentor': typeof MentorRoute
  '/playground': typeof PlaygroundRoute
  '/practice': typeof PracticeRoute
  '/progress': typeof ProgressRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/quizzes': typeof QuizzesRouteWithChildren
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/statistics': typeof StatisticsRoute
  '/debug-lab/$bugId': typeof DebugLabBugIdRoute
  '/interview/session': typeof InterviewSessionRoute
  '/learn/lessons': typeof LearnLessonsRoute
  '/learn/modules': typeof LearnModulesRoute
  '/learn/topics': typeof LearnTopicsRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/quizzes/$quizId': typeof QuizzesQuizIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/bookmarks': typeof BookmarksRoute
  '/challenges': typeof ChallengesRoute
  '/debug-lab': typeof DebugLabRouteWithChildren
  '/docs': typeof DocsRoute
  '/flashcards': typeof FlashcardsRoute
  '/interview': typeof InterviewRouteWithChildren
  '/learn': typeof LearnRouteWithChildren
  '/mentor': typeof MentorRoute
  '/playground': typeof PlaygroundRoute
  '/practice': typeof PracticeRoute
  '/progress': typeof ProgressRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/quizzes': typeof QuizzesRouteWithChildren
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/statistics': typeof StatisticsRoute
  '/debug-lab/$bugId': typeof DebugLabBugIdRoute
  '/interview/session': typeof InterviewSessionRoute
  '/learn/lessons': typeof LearnLessonsRoute
  '/learn/modules': typeof LearnModulesRoute
  '/learn/topics': typeof LearnTopicsRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/quizzes/$quizId': typeof QuizzesQuizIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/bookmarks': typeof BookmarksRoute
  '/challenges': typeof ChallengesRoute
  '/debug-lab': typeof DebugLabRouteWithChildren
  '/docs': typeof DocsRoute
  '/flashcards': typeof FlashcardsRoute
  '/interview': typeof InterviewRouteWithChildren
  '/learn': typeof LearnRouteWithChildren
  '/mentor': typeof MentorRoute
  '/playground': typeof PlaygroundRoute
  '/practice': typeof PracticeRoute
  '/progress': typeof ProgressRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/quizzes': typeof QuizzesRouteWithChildren
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/statistics': typeof StatisticsRoute
  '/debug-lab/$bugId': typeof DebugLabBugIdRoute
  '/interview/session': typeof InterviewSessionRoute
  '/learn/lessons': typeof LearnLessonsRoute
  '/learn/modules': typeof LearnModulesRoute
  '/learn/topics': typeof LearnTopicsRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/quizzes/$quizId': typeof QuizzesQuizIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/achievements'
    | '/bookmarks'
    | '/challenges'
    | '/debug-lab'
    | '/docs'
    | '/flashcards'
    | '/interview'
    | '/learn'
    | '/mentor'
    | '/playground'
    | '/practice'
    | '/progress'
    | '/projects'
    | '/quizzes'
    | '/resources'
    | '/settings'
    | '/statistics'
    | '/debug-lab/$bugId'
    | '/interview/session'
    | '/learn/lessons'
    | '/learn/modules'
    | '/learn/topics'
    | '/lesson/$lessonId'
    | '/projects/$projectId'
    | '/quizzes/$quizId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/achievements'
    | '/bookmarks'
    | '/challenges'
    | '/debug-lab'
    | '/docs'
    | '/flashcards'
    | '/interview'
    | '/learn'
    | '/mentor'
    | '/playground'
    | '/practice'
    | '/progress'
    | '/projects'
    | '/quizzes'
    | '/resources'
    | '/settings'
    | '/statistics'
    | '/debug-lab/$bugId'
    | '/interview/session'
    | '/learn/lessons'
    | '/learn/modules'
    | '/learn/topics'
    | '/lesson/$lessonId'
    | '/projects/$projectId'
    | '/quizzes/$quizId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/achievements'
    | '/bookmarks'
    | '/challenges'
    | '/debug-lab'
    | '/docs'
    | '/flashcards'
    | '/interview'
    | '/learn'
    | '/mentor'
    | '/playground'
    | '/practice'
    | '/progress'
    | '/projects'
    | '/quizzes'
    | '/resources'
    | '/settings'
    | '/statistics'
    | '/debug-lab/$bugId'
    | '/interview/session'
    | '/learn/lessons'
    | '/learn/modules'
    | '/learn/topics'
    | '/lesson/$lessonId'
    | '/projects/$projectId'
    | '/quizzes/$quizId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AchievementsRoute: typeof AchievementsRoute
  BookmarksRoute: typeof BookmarksRoute
  ChallengesRoute: typeof ChallengesRoute
  DebugLabRoute: typeof DebugLabRouteWithChildren
  DocsRoute: typeof DocsRoute
  FlashcardsRoute: typeof FlashcardsRoute
  InterviewRoute: typeof InterviewRouteWithChildren
  LearnRoute: typeof LearnRouteWithChildren
  MentorRoute: typeof MentorRoute
  PlaygroundRoute: typeof PlaygroundRoute
  PracticeRoute: typeof PracticeRoute
  ProgressRoute: typeof ProgressRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  QuizzesRoute: typeof QuizzesRouteWithChildren
  ResourcesRoute: typeof ResourcesRoute
  SettingsRoute: typeof SettingsRoute
  StatisticsRoute: typeof StatisticsRoute
  LessonLessonIdRoute: typeof LessonLessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes': {
      id: '/quizzes'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof QuizzesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor': {
      id: '/mentor'
      path: '/mentor'
      fullPath: '/mentor'
      preLoaderRoute: typeof MentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview': {
      id: '/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof InterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards': {
      id: '/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug-lab': {
      id: '/debug-lab'
      path: '/debug-lab'
      fullPath: '/debug-lab'
      preLoaderRoute: typeof DebugLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/$quizId': {
      id: '/quizzes/$quizId'
      path: '/$quizId'
      fullPath: '/quizzes/$quizId'
      preLoaderRoute: typeof QuizzesQuizIdRouteImport
      parentRoute: typeof QuizzesRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/lesson/$lessonId': {
      id: '/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/lesson/$lessonId'
      preLoaderRoute: typeof LessonLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/topics': {
      id: '/learn/topics'
      path: '/topics'
      fullPath: '/learn/topics'
      preLoaderRoute: typeof LearnTopicsRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/modules': {
      id: '/learn/modules'
      path: '/modules'
      fullPath: '/learn/modules'
      preLoaderRoute: typeof LearnModulesRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/lessons': {
      id: '/learn/lessons'
      path: '/lessons'
      fullPath: '/learn/lessons'
      preLoaderRoute: typeof LearnLessonsRouteImport
      parentRoute: typeof LearnRoute
    }
    '/interview/session': {
      id: '/interview/session'
      path: '/session'
      fullPath: '/interview/session'
      preLoaderRoute: typeof InterviewSessionRouteImport
      parentRoute: typeof InterviewRoute
    }
    '/debug-lab/$bugId': {
      id: '/debug-lab/$bugId'
      path: '/$bugId'
      fullPath: '/debug-lab/$bugId'
      preLoaderRoute: typeof DebugLabBugIdRouteImport
      parentRoute: typeof DebugLabRoute
    }
  }
}

interface DebugLabRouteChildren {
  DebugLabBugIdRoute: typeof DebugLabBugIdRoute
}

const DebugLabRouteChildren: DebugLabRouteChildren = {
  DebugLabBugIdRoute: DebugLabBugIdRoute,
}

const DebugLabRouteWithChildren = DebugLabRoute._addFileChildren(
  DebugLabRouteChildren,
)

interface InterviewRouteChildren {
  InterviewSessionRoute: typeof InterviewSessionRoute
}

const InterviewRouteChildren: InterviewRouteChildren = {
  InterviewSessionRoute: InterviewSessionRoute,
}

const InterviewRouteWithChildren = InterviewRoute._addFileChildren(
  InterviewRouteChildren,
)

interface LearnRouteChildren {
  LearnLessonsRoute: typeof LearnLessonsRoute
  LearnModulesRoute: typeof LearnModulesRoute
  LearnTopicsRoute: typeof LearnTopicsRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnLessonsRoute: LearnLessonsRoute,
  LearnModulesRoute: LearnModulesRoute,
  LearnTopicsRoute: LearnTopicsRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface QuizzesRouteChildren {
  QuizzesQuizIdRoute: typeof QuizzesQuizIdRoute
}

const QuizzesRouteChildren: QuizzesRouteChildren = {
  QuizzesQuizIdRoute: QuizzesQuizIdRoute,
}

const QuizzesRouteWithChildren =
  QuizzesRoute._addFileChildren(QuizzesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AchievementsRoute: AchievementsRoute,
  BookmarksRoute: BookmarksRoute,
  ChallengesRoute: ChallengesRoute,
  DebugLabRoute: DebugLabRouteWithChildren,
  DocsRoute: DocsRoute,
  FlashcardsRoute: FlashcardsRoute,
  InterviewRoute: InterviewRouteWithChildren,
  LearnRoute: LearnRouteWithChildren,
  MentorRoute: MentorRoute,
  PlaygroundRoute: PlaygroundRoute,
  PracticeRoute: PracticeRoute,
  ProgressRoute: ProgressRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  QuizzesRoute: QuizzesRouteWithChildren,
  ResourcesRoute: ResourcesRoute,
  SettingsRoute: SettingsRoute,
  StatisticsRoute: StatisticsRoute,
  LessonLessonIdRoute: LessonLessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
